version: 10.0.{build}.0
skip_tags: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
init:
- cmd: nuget sources add -Name Episerver -Source http://nuget.episerver.com/feed/packages.svc/
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  project_feed: true
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  verbosity: minimal
