name: Release build

#on:
#  push:
#    branches:    
#      - master         # Push events on master branch
#      - 'release/*'   # Push events to branches matching refs/heads/releases/*
    # Sequence of patterns matched against refs/tags
#    tags:        
#      - v1             # Push events to v1 tag
#      - v1.0           # Push events to v1.0 tag
#      - 'test*'

on:
  push: 
    branches: 
      - refs/tags/*
      
jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: warrenbuckley/Setup-Nuget@v1
    - uses: warrenbuckley/Setup-MSBuild@v1
    - uses: actions/setup-dotnet@v1

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"

    - name: Nuget restore
      run: nuget restore Epinova.QuickExport.sln
     
    - name: MSBuild
      run: msbuild Epinova.QuickExport.sln -p:Configuration=Release

#    - name: Run tests
#      run: dotnet test

    - name: Nuget pack
      run: nuget pack src/Epinova.QuickExport/Epinova.QuickExport.csproj -Properties Configuration=Release -OutputDirectory dist
      
