name: CI

on:
  push:
    branches:
    - release/*
    
jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
      
    - name: Nuget restore
      run: nuget restore Epinova.QuickExport.sln
      
    - name: MSBuild
      run: msbuild Epinova.QuickExport.sln
